Tejas/fourth example
TejasSC/Haskell-Weeks-1to4-coding-tasks pull request #5
Opened 2018-06-29 08:22 UTC by TejasSC

http://www.seas.upenn.edu/~cis194/spring13/hw/04-higher-order.pdf

2018-06-29 09:53 UTC, chshersh requested changes

2018-06-29 09:53 UTC, chshersh commented on Golf.hs
> +module Golf where
It's strange that this file in this commit because it's related to previous homework. Usually, when you're working with git the workflow is the following:

```shell
$ git checkout master  # switch to master branch
$ git pull -r  # fetch all changes from remote repository
$ git checkout -b myname/issue-name  # create new branch starting from most latest version of repository
```

This workflow helps to maintain good commit history. It's okay for this pull request but in future it's better to use workflow described above.

2018-06-29 09:53 UTC, chshersh commented on WeekFour.hs
> +fun1' = product . map (\x -> x-2) . filter (even)
`()` around `even` are redundant here.

Also, `\x -> x - 2` lambda function can be written in point-free style. Use `subtract` function.

2018-06-29 09:53 UTC, chshersh commented on WeekFour.hs
> +fun2' = sum . gatherNums
You need to implement this function using `iterate` function. It might be difficult at first. But I think that this is a good exercise.

2018-06-29 09:53 UTC, chshersh commented on WeekFour.hs
> +        right  = buildFromSorted $ drop (middle + 1) list
Instead of using `drop` and `while` function try to use `splitAt` function + pattern-matching to avoid traversing prefix of the list twice.

2018-06-29 09:53 UTC, chshersh commented on WeekFour.hs
> +        height = floor $ logBase 2 (fromIntegral $ length list)
I think here it's better to call `height` function explicitly on children to calculate result. But this homework this implementation is good as well.

2018-06-29 09:53 UTC, ChShersh commented on WeekFour.hs
> +funcXOR a b = (a && (not b)) || ((not a) && b)
This function can be written shorter, it's just `(/=)` operator 😉

2018-06-29 09:53 UTC, ChShersh commented on WeekFour.hs
> +xor (x:xs) = foldr (funcXOR) x xs
Try to write `xor` without pattern-matching on list. It's possible.

2018-06-29 09:53 UTC, ChShersh commented on WeekFour.hs
> +map' f xs = foldr (\x xs -> (f x):xs) [] xs
Again, you don't need case for empty list, you can write this function in single line.

2018-07-01 00:27 UTC, TejasSC commented on Golf.hs
> +module Golf where
Very sorry about that, purely a unintentional mistake on my part. 
Will rectify this ASAP.

2018-07-02 01:57 UTC, ChShersh commented on Golf.hs
> +module Golf where
Don't bother with prettifying commit history in this PR! Unfortunately, `git` is not very convenient system. It's pretty easy to mess up with and pretty hard to clean mess after that. So don't spend time on this one. But be careful in future.

2018-07-02 04:25 UTC, chshersh approved these changes

2018-07-02 04:25 UTC, merged